config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  scope "/admin" do
    resources :users do
      member do
        post :restore
        put :accept
      end
    end
  end

  resources :tags

  resources :companies do
    member do
      put :join
    end
  end

  resources :clients do
    resources :notes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :client
  belongs_to :user

  validates :body, :client, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_client
  before_action :set_note, only: %i[edit update destroy]
  before_action :authorize_note, only: %i[edit update destroy]
  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  # GET /notes or /notes.json
  def index
    @notes = policy_scope(@client.notes).order("created_at DESC").page(params[:page])
    authorize(@client)
  end

  # GET /notes/new
  def new
    @note = @client.notes.build
    authorize_note
  end

  # POST /notes or /notes.json
  def create
    @note = @client.notes.build(note_params.merge(user: current_user))
    authorize_note
    if @note.save
      redirect_to client_notes_path, notice: "Note was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    if @note.update(note_params)
      redirect_to client_notes_path, notice: "Note was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    redirect_to client_notes_path(@client), notice: "Note was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = policy_scope(@client.notes).find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to client_notes_path
  end

  # Only allow a list of trusted parameters through.
  def note_params
    params.require(:note).permit(:body, :client_id, :user_id)
  end

  def set_client
    @client = Client.find(params[:client_id])
  end

  def authorize_note
    authorize(@note)
  end
end

app/views/notes/_form.html.erb
<%= form_with model: [@client, note] do |form| %>
  <% if note.errors.any? %>
    <div class="form-error">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :body, 'Text', class: "form-label" %>
    <%= form.text_area :body, class: "form-input min-h-[200px]" %>  </div>
  <div>
    <%= form.submit class: "btn w-full" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="m-6">
  <div>
    <%= link_to "< Back to notes", client_notes_path, class: "text-sinaptia-2 font-medium" %>
  </div>
  
  <div class="form-tables">

  <h2 class="form-title">Edit note for <%= @client.name %></h2>
  
  <%= render "form", note: @note %>
  
  <br>
  
  </div>
</div>

app/views/notes/index.html.erb
<div class="flex flex-row justify-between items-center p-3 my-4">
  <h2 class="text-gray-700 dark:text-white font-semibold text-3xl"> <%= pluralize(@notes.count, "Note") %> for <%= @client.name%> </h2>
  <%= link_to "New note", new_client_note_path, class: "btn" %>
</div>
<% if @notes.any? %>
  <div id="notes" >
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <table class="w-full text-sm text-left text-gray-700 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-200 dark:bg-neutral-800 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">Date</th>
            <th scope="col" class="px-6 py-3">Created By</th>
            <th scope="col" class="px-6 py-3">Text</th>
            <th scope="col" class="px-6 py-3"></th>
          </tr>
        </thead>
        <tbody>
          <% @notes.each do |note| %>
            <tr class="bg-white border-b dark:bg-zinc-500 dark:border-gray-700 dark:text-white" id="<%= dom_id note %>">
              <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                <%= note.created_at.strftime('%m/%d/%Y') %>
              </td>
              <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                <%= note.user.email %>
              </td>
              <td class="px-6 py-4"> <%= note.body %></td>
              <td class="px-6 py-4">
                <div class="flex flex-row">
                  <% if policy(note).edit? %>
                    <%= link_to "Edit", edit_client_note_path(@client, note), class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                  <% end %>
                  <% if policy(note).destroy? %>
                    <%= link_to "Delete", client_note_path(@client, note), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%# Pagination %>
      <div class="p-2 dark:bg-neutral-800">
        <span class="text-sm font-normal text-gray-500 dark:text-gray-400"><%= page_entries_info @notes %></span>
        <%= paginate @notes, left: 1, right: 3 %>
      </div>
    </div>
  </div>
<% end %>

app/views/notes/new.html.erb
<div class="m-6">
  <div>
    <%= link_to "< Back to notes", client_notes_path, class: "text-sinaptia-2 font-medium" %>
  </div>

  <div class="form-tables">
    <h2 class="form-title">New note for <%= @client.name %></h2>

    <%= render "form", note: @note %>

    <br>
  </div>
</div>