config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  scope "/admin" do
    resources :users do
      member do
        post :restore
        put :accept
      end
    end
  end

  resources :tags

  resources :companies do
    member do
      put :join
    end
  end

  resources :clients do
    resources :notes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/user.rb
class User < ApplicationRecord
  include Discard::Model
  include PgSearch::Model
  pg_search_scope :search, against: [:email, :first_name, :last_name], using: {tsearch: {prefix: true}}

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :notes
  has_many :identities
  belongs_to :company, optional: true

  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true

  enum role: {default: 0, admin: 1}

  def belongs_company?(id)
    company.id == id
  end

  def active_for_authentication?
    super && !discarded?
  end

  def has_company?
    !company.nil? && accepted
  end

  private

  def domain_check
    unless APPROVED_DOMAINS.any? { |word| email.end_with?(word) }
      errors.add(:email, "is not from a valid domain")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :auth
  def google_oauth2
    omniauth_authentication
  end

  private

  def omniauth_authentication
    @identity = Identity.find_or_create_by uid: @auth["uid"], provider: @auth["provider"]

    @identity.update auth_data: @auth.as_json

    if signed_in?
      if @identity.user == current_user
        redirect_to root_path, notice: t(".already_linked")
      else
        @identity.update user: current_user
        redirect_to root_path, notice: t(".successfully_linked")
      end
    elsif @identity.user.blank?
      @user = User.find_or_initialize_by email: @auth.dig("info", "email")
      @user.validate
      if @user.errors[:email].any?
        redirect_to root_path, notice: t(".successfully_linked") and return
      end
      @user.update(first_name: @auth.dig("info", "first_name"), last_name: @auth.dig("info", "last_name"), password: Devise.friendly_token[0, 20], role: "default") if @user.new_record?

      @identity.update user: @user

      sign_in @identity.user
      redirect_to root_path
    else
      sign_in_and_redirect @identity.user
    end
  end

  def auth
    @auth ||= request.env["omniauth.auth"]
  end
end

app/controllers/users/registrations_controller.rb
# app/controllers/registrations_controller.rb (si estás usando Devise)
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_user_session_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    if resource.has_company?
      clients_path
    else
      companies_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_company
  before_action :set_user, only: %i[edit update destroy restore accept]
  before_action :authorize_user, only: %i[edit update destroy restore accept]
  after_action :verify_authorized

  # GET /users
  def index
    @users = User.excluding(current_user).where(company: @company).page(params[:page])
    if params[:search].present?
      @users = @users.search(params[:search])
    end
    authorize(User)
  end

  def new
    @user = User.new
    authorize_user
  end

  def create
    @user = User.new(user_params.merge(company: @company, accepted: true))
    authorize_user
    if @user.save
      redirect_to users_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.discard
    redirect_to users_path, notice: "User was successfully deleted."
  end

  # RESTORE /users/1
  def restore
    @user.undiscard
    redirect_to users_path, notice: "User was successfully restored."
  end

  def accept
    if @user.update(accepted: true)
      redirect_to users_path, notice: "User was accepted in the company"
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password, :role, :first_name, :last_name)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user
    authorize(@user)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= render "users/shared/error_messages", resource: user %>

  <% if user.new_record? %>
    <div>
      <%= form.label :email, class:"form-label" %>
      <%= form.email_field :email, autofocus: true, class:"form-input" %>
    </div>
    
    <div>
      <%= form.label :password, class:"form-label" %>
      <%= form.password_field :password, class:"form-input" %>
    </div>
  <% end%>
  
  <div>
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-input" %>
  </div>
  
  <div>
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-input" %>
  </div>
  
  <div class="flex justify-center items-center my-2">
    <%= form.label :role, 'Admin', class: "form-label m-2" %>
    <%= form.check_box :role, { checked: user.admin? }, 'admin', 'default'  %>
  </div>

<%= form.submit class: "btn my-2 w-full" %>

<% end %>

app/views/users/edit.html.erb
<div class="m-6">
  
  <div>
    <%= link_to "< Back to users", users_path, class: "text-sinaptia-2 font-medium" %>
  </div>
  
  <div class="form-tables">
    <h2 class="form-title">Edit user</h2>

    <%= render "form", user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<div class="flex flex-row justify-between items-center p-3 my-4">
  <h2 class="text-gray-700 dark:text-white font-semibold text-3xl">Users</h2>
  <%= link_to "New user", new_user_path, class: "btn" %>
</div>

<%= form_tag(users_path, method: :get) do %>
  <%= render "shared/search", search_fields: 'Email, First Name, Last Name' %>
<% end %>

<div id="clients">
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-700 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-200 dark:bg-neutral-800 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3">Email</th>
          <th scope="col" class="px-6 py-3">First Name</th>
          <th scope="col" class="px-6 py-3">Last Name</th>
          <th scope="col" class="px-6 py-3">Role</th>
          <th scope="col" class="px-6 py-3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr
            class="bg-white border-b dark:bg-zinc-500 dark:border-neutral-800 dark:text-white"
            id="<%= dom_id user %>"
          >
            <td
              scope="row"
              class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
            >
              <%= user.email %>
            </td>
            <td class="px-6 py-4"><%= user.first_name %></td>
            <td class="px-6 py-4"><%= user.last_name %></td>
            <td class="px-6 py-4 uppercase">
              <span class="tag m-0"><%= user.role %></span>
            </td>
            <td class="px-6 py-4">
              <% if user.accepted? %>
                <div class="flex flex-row">
                  <% if policy(user).edit? %>
                    <%= link_to "Edit", edit_user_path(user), class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                  <% end %>
                  <% if policy(user).destroy? %>
                    <%= link_to "Delete", user_path(user), data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this user?'}, class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                  <% end %>
                  <% if policy(user).restore? %>
                    <%= link_to "Restore", restore_user_path(user), data: {turbo_method: :post, turbo_confirm: 'Are you sure you want to restore this user?'}, class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                  <% end %>
                </div>
              <% else %>
                <div class="flex flex-row">
                  <%= link_to "Accept", accept_user_path(user), data: {turbo_method: :put, turbo_confirm: 'Are you sure you want to accept this user?'}, class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%# Pagination %>
    <div class="p-2 dark:bg-neutral-800">
      <span class="text-sm font-normal text-gray-500 dark:text-gray-400"><%= page_entries_info @users %></span>
      <%= paginate @users, left: 1, right: 3 %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="m-6">
  <div>
    <%= link_to "< Back to users", users_path, class: "text-sinaptia-2 font-medium" %>
  </div>
  
  <div class="form-tables">
    <h2 class="form-title">New user</h2>
  
    <%= render "form", user: @user %>
  </div>
</div>