config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  scope "/admin" do
    resources :users do
      member do
        post :restore
        put :accept
      end
    end
  end

  resources :tags

  resources :companies do
    member do
      put :join
    end
  end

  resources :clients do
    resources :notes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/views/shared/_navbar.html.erb
<% if user_signed_in? %> 
<nav class="bg-white border-gray-200 px-2 sm:px-4 dark:bg-neutral-800 shadow">
  <div class="container flex flex-wrap items-center justify-between max-w-7xl mx-auto">
    <div class="flex items-center">
      <a href="/">
        <%= image_tag("sinaptia_logo.svg", class: "w-16 h-16", alt: "sinaptia_logo.svg") %>
      </a>
    </div>
    <div class="flex items-center md:order-2">
      <label class="relative inline-flex items-center my-4 mx-3 cursor-pointer">
        <input type="checkbox" id="dark-toggle-switch" value="" class="sr-only peer">
        <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-gray-300 dark:peer-focus:ring-gray-500 dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-gray-600"></div>
      </label>      
      <button
        type="button"
        class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
        id="user-menu-button"
        aria-expanded="false"
        data-dropdown-toggle="user-dropdown"
        data-dropdown-placement="bottom"
      >
        <span class="sr-only">Open user menu</span>
        <%= image_tag("blank-profile-picture.webp", class: "w-8 h-8 rounded-full", alt: "user photo") %>
      </button>
      <!-- Dropdown menu -->
      <div
        class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-zinc-700 dark:divide-gray-600 shadow-md"
        id="user-dropdown"
      >
        <div class="px-4 py-3">
          <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= current_user && current_user.email %></span>
          <% if current_user.has_company? %>
            <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= current_user.company.name %></span>
          <% end %>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "block w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"%> 
          </li>
        </ul>
      </div>
      <button
        data-collapse-toggle="mobile-menu-2"
        type="button"
        class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
        aria-controls="mobile-menu-2"
        aria-expanded="false"
      >
        <span class="sr-only">Open main menu</span>
        <svg
          class="w-6 h-6"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="mobile-menu-2">
      <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-white md:flex-row md:space-x-8 md:items-center md:h-16 md:mt-0 md:p-0 md:text-sm md:font-medium md:border-0 dark:bg-neutral-800 dark:border-gray-700">
        <% if policy(:user).index? %>
          <li class="h-full">
            <%= link_to "Users", users_path, class: "nav-link h-full" %>
          </li>
        <% end %>
        <% if policy(:client).index? %>
          <li class="h-full">
            <%= link_to "Clients", clients_path, class: "nav-link h-full" %>
          </li>
        <% end %>
        <% if policy(:tag).index? %>
          <li class="h-full">
            <%= link_to "Tags", tags_path, class: "nav-link h-full" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/shared/_search.html.erb
<form class="my-4">   
  <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
  <div class="relative">
    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
      <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
    </div>
    <%= text_field_tag(:search, params[:search], class: "block w-full my-4 p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-sinaptia-2 focus:border-sinaptia-2 dark:bg-zinc-500 dark:border-neutral-800 dark:placeholder-gray-300 dark:text-white dark:focus:ring-sinaptia-2 dark:focus:border-sinaptia-2", placeholder: "Search by #{search_fields}..." ) %>
    <%= submit_tag("Search", class: "btn absolute right-2.5 bottom-2.5 text-sm") %>
  </div>
  <% if params[:search] %>
    <p class="text-gray-700 dark:text-white my-4">Search results for: <b><%= params[:search] %></b></p>
  <% end %>
</form>
