config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  scope "/admin" do
    resources :users do
      member do
        post :restore
        put :accept
      end
    end
  end

  resources :tags

  resources :companies do
    member do
      put :join
    end
  end

  resources :clients do
    resources :notes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search, against: [:name], using: {tsearch: {prefix: true}}

  has_and_belongs_to_many :clients
  belongs_to :company

  validates :name, presence: true, uniqueness: {scope: :company_id}

  def belongs_company?(id)
    company.id == id
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[edit update destroy]
  before_action :authorize_tag, only: %i[edit update destroy]
  before_action :set_company
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  # GET /tags
  def index
    @tags = policy_scope(Tag).where(company: @company).page(params[:page])
    if params[:search].present?
      @tags = @tags.search(params[:search])
    end
  end

  # GET /tags/new
  def new
    @tag = Tag.new
    authorize_tag
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params.merge(company: @company))
    authorize_tag
    if @tag.save
      redirect_to tags_url, notice: "Tag was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to tags_url, notice: "Tag was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: "Tag was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = policy_scope(Tag).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name)
  end

  def authorize_tag
    authorize(@tag)
  end
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div class="form-error">
      <h2><%= pluralize(tag.errors.count, "error") %>
        prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-input" %>
  </div>

  <div>
    <%= form.submit class: "btn w-full" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<div class="m-6">
  <div>
    <%= link_to "< Back to tags", tags_path, class: "text-sinaptia-2 font-medium"  %>
  </div>

  <div class="form-tables">
    <h2 class="form-title">Edit tag</h2>

    <%= render "form", tag: @tag %>

    <br>
  </div>
</div>

app/views/tags/index.html.erb
<div class="flex flex-row justify-between items-center p-3 my-4">
  <h2 class="text-gray-700 dark:text-white font-semibold text-3xl">Tags</h2>
  <%= link_to "New tag", new_tag_path, class: "btn" %>
</div>

<%= form_tag(tags_path, method: :get) do %>
  <%= render "shared/search", search_fields: 'Name' %>
<% end %>

<div class="relative mb-16 overflow-x-auto shadow-md sm:rounded-lg">

  <table class="w-full text-sm text-left text-gray-700 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-200 dark:bg-neutral-800 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">Name</th>
      </tr>
    </thead>
    <tbody>
      <% @tags.each_with_index do |tag, index| %>
        <tr class="bg-white border-b dark:bg-zinc-500 dark:border-neutral-800 dark:text-white" id="<%= dom_id tag %>">
          <td scope="row" class=" font-medium text-gray-900 whitespace-nowrap dark:text-white">
              <div class="flex flex-row items-center justify-between">
                <p class="px-6 py-4"><%= tag.name %></p>
                <div class="flex flex-row">
                <% if policy(tag).update? %>
                  <%= link_to "Edit", edit_tag_path(tag), class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                <% end %>
                <% if policy(tag).destroy? %>
                  <%= link_to "Delete", tag, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "mx-3 font-medium text-sinaptia-2 dark:text-sinaptia-2 hover:underline uppercase" %>
                <% end %>
                </div>
              </div> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="p-2 dark:bg-neutral-800">
    <span class="text-sm font-normal text-gray-500 dark:text-gray-400"><%= page_entries_info @tags %></span>
    <%= paginate @tags, left: 1, right: 3 %>
  </div>
</div>

app/views/tags/new.html.erb
<div class="m-6">
  <div>
    <%= link_to "< Back to tags", tags_path, class: "text-sinaptia-2 font-medium"  %>
  </div>

  <div class="form-tables">
    <h2 class="form-title">New Tag</h2>

    <%= render "form", tag: @tag %>

    <br>
  </div>
</div>